# Generated by Django 4.2.6 on 2023-11-11 23:11

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=256, validators=[users.validators.is_valid_password]),
        ),
    ]
