# Generated by Django 4.2.6 on 2023-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_status',
            field=models.CharField(choices=[('EMAIL_VERIFIED', 'EMAIL_VERIFIED'), ('EMAIL_PENDING', 'EMAIL_PENDING')], default='EMAIL_PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_status',
            field=models.CharField(choices=[('PHONE_VERIFIED', 'PHONE_VERIFIED'), ('PHONE_PENDING', 'PHONE_PENDING')], default='PHONE_PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('CARD_ID_PENDING', 'CARD_ID_PENDING')], default='INACTIVE', max_length=30),
        ),
    ]
