# Generated by Django 4.2.6 on 2023-11-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='ManagerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(choices=[(25, '25 per month'), (50, '50 per month'), (80, '80 per month')], decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('manager_id', models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
            options={
                'db_table': 'manager_subscription',
            },
        ),
    ]
