# Generated by Django 4.2.6 on 2023-11-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hair_salons', '0001_initial'),
        ('users', '0002_user_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairdresser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hair_salon_id', models.ForeignKey(db_column='hair_salon_id', on_delete=django.db.models.deletion.CASCADE, to='hair_salons.hairsalon')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'hairdresser',
            },
        ),
    ]
